const express = require('express');

const app = express();
app.use(express.json()); // Middleware to parse JSON bodies

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Backend running on http://localhost:${PORT}`);
});

app.get('/', (req, res) => {
  res.send('Hello from the backend!');
 
});

//Sample in-memory data store
let items = [];

// Create Item

app.post('/create', (req, res) => {

  const { title, description } = req.body;
  // Logic to create an item in the database
  const newItem = { 
    id: items.length+1, // In a real application, this would be generated by the database
     title,
      description };

      items.push(newItem);
      console.log(items);

  res.status(201).json( newItem);
 
});

app.get('/create', (req, res) => {
  res.json(items);
});


